security:
  user:
    password: secret
  oauth2:
    client:
      clientId: myclient
      clientSecret: mysecret
      scope: access
      auto-approve-scopes: '.*'
    authorization:
      checkTokenAccess: permitAll()
